version: '3.5'

services:
  lumen:
    ports:
      - "8005:8005"
    volumes:
      - .:/var/www/html
      - /var/www/html/shipment-service/
    build: .
    command: php -S lumen:8005 -t public

    restart: always
